spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: jdbc:h2:mem:librairyDB
    dbcp2:
      driver-class-name: org.h2.Driver
      username: sa
      password:     
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  main:
    lazy-initialization: true


   
server:
  port: 8080